services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
